name: CI
on: 
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest ] # More distributions can be added in the future
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'debian-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake libbluetooth-dev libsdl-dev freeglut3-dev
      - name: Build (shared lib)
        run: | 
          cmake -B build-shared -DBUILD_SHARED_LIBS=TRUE
          cmake --build build-shared
      - name: Build (static lib)
        run: |
          cmake -B build-static
          cmake --build build-static
          
      - name: Upload (shared lib)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }} shared lib
          path: build-shared/src/libwiiuse.so
      - name: Upload (static lib)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }} static lib
          path: build-static/src/libwiiuse.a

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew update
          brew install cmake freeglut sdl
      - name: Build (shared lib)
        run: | 
          cmake -B build-shared -DBUILD_SHARED_LIBS=TRUE
          cmake --build build-shared
      - name: Build (static lib)
        run: |
          cmake -B build-static
          cmake --build build-static
          
      - name: Upload (shared lib)
        uses: actions/upload-artifact@v2
        with:
          name: MacOS shared lib
          path: build-shared/src/libwiiuse.dylib
      - name: Upload (static lib)
        uses: actions/upload-artifact@v2
        with:
          name: MacOS static lib
          path: build-static/src/libwiiuse.a


  build-windows:
  
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build (shared lib)
        run: |
          cmake -B build-shared -DBUILD_SHARED_LIBS=TRUE
          cmake --build build-shared
      - name: Build (static lib)
        run: |
          cmake -B build-static
          cmake --build build-static
          
      - name: ls
        run: ls */*/*/*
